name: Build Counters App and publish to fly.io

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  frontend-tests:
    runs-on: ubuntu-20.04 
    steps:
      - name: Checkout repository for frontend test
        uses: actions/checkout@v3
      - name: Setup Node environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: |
          cd counters-frontend
          npm install
      - name: Check with eslint
        run: |
          cd counters-frontend
          npm run lint
      - name: Component tests with jest
        run: |
          cd counters-frontend
          npm run test
  backend-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository for backend
        uses: actions/checkout@v3
      - name: Setup Node environment
        uses: actions/setup-node@v3
      - name: Install backend dependencies
        run: |
          cd counters-backend
          npm install
      - name: Check with eslint
        run: |
          cd counters-backend
          npm run lint
      - name: Component tests with jest
        run: |
          cd counters-backend
          npm run test
  deploy:
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') }}
    needs:
      - frontend-tests
      - backend-tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository for deploy
        uses: actions/checkout@v3
      - name: Setup deploy to fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy app to fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  tag-release:
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') }}
    needs:
      - deploy
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout for tagging
        uses: actions/checkout@v3
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.55.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
